# Цель лабораторной работы
Изучить библиотеки обработки данных Pandas и PandaSQL.

# Задание
Задание состоит из&nbsp;двух частей.

## Часть 1
Требуется выполнить первое демонстрационное задание под&nbsp;названием «Exploratory data analysis with Pandas» со&nbsp;страницы курса [mlcourse.ai](https://mlcourse.ai/assignments).

## Часть 2
Требуется выполнить следующие запросы с&nbsp;использованием двух различных библиотек&nbsp;— Pandas и PandaSQL:

- один произвольный запрос на соединение двух наборов данных,
- один произвольный запрос на группировку набора данных с использованием функций агрегирования.

Также требуется сравнить время выполнения каждого запроса в&nbsp;Pandas и PandaSQL.

## Часть 1

In [21]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv('nyc-jobs.csv')
data.head()

,Job ID,Agency,Posting Type,# Of Positions,Business Title,Civil Service Title,Title Code No,Level,Job Category,Full-Time/Part-Time indicator,...,Additional Information,To Apply,Hours/Shift,Work Location 1,Recruitment Contact,Residency Requirement,Posting Date,Post Until,Posting Updated,Process Date
0,87990,DEPARTMENT OF BUSINESS SERV.,Internal,1,Account Manager,CONTRACT REVIEWER (OFFICE OF L,40563,1,NaN,NaN,...,"Salary range for this position is: $42,405 - $...",NaN,NaN,NaN,NaN,New York City residency is generally required ...,2011-06-24T00:00:00.000,NaN,2011-06-24T00:00:00.000,2019-03-19T00:00:00.000
1,97899,DEPARTMENT OF BUSINESS SERV.,Internal,1,"EXECUTIVE DIRECTOR, BUSINESS DEVELOPMENT",ADMINISTRATIVE BUSINESS PROMOT,10009,M3,NaN,F,...,NaN,"In addition to applying through this website, ...",NaN,NaN,NaN,New York City residency is generally required ...,2012-01-26T00:00:00.000,NaN,2012-01-26T00:00:00.000,2019-03-19T00:00:00.000
2,132292,NYC HOUSING AUTHORITY,External,52,Maintenance Worker - Technical Services-Heatin...,MAINTENANCE WORKER,90698,0,Maintenance & Operations,F,...,1. A Motor Vehicle Driverâ€™s License valid i...,"Click the ""Apply Now"" button.",NaN,NaN,NaN,NYCHA has no residency requirements.,2013-10-24T00:00:00.000,NaN,2013-12-12T00:00:00.000,2019-03-19T00:00:00.000
3,132292,NYC HOUSING AUTHORITY,Internal,52,Maintenance Worker - Technical Services-Heatin...,MAINTENANCE WORKER,90698,0,Maintenance & Operations,F,...,1. A Motor Vehicle Driverâ€™s License valid i...,"Click the ""Apply Now"" button.",NaN,NaN,NaN,NYCHA has no residency requirements.,2013-10-24T00:00:00.000,NaN,2013-12-12T00:00:00.000,2019-03-19T00:00:00.000
4,133921,NYC HOUSING AUTHORITY,Internal,50,Temporary Painter,PAINTER,91830,0,Maintenance & Operations,F,...,SPECIAL NOTE: 1. This is a temporary assig...,"Click the ""Apply Now"" button.",NaN,NaN,NaN,NYCHA has no residency requirement.,2014-01-09T00:00:00.000,NaN,2014-01-08T00:00:00.000,2019-03-19T00:00:00.000

In [5]:
data['Level'].value_counts()

0     1428
1      801
2      632
3      388
M1     171
M2     125
M3      96
4       64
M4      50
M5      33
M7      12
4B      11
M6      10
4A       8
3A       4
1B       4
M8       2
M9       2
1A       2
Name: Level, dtype: int64

In [8]:
data.loc[data['Level'] == 'M6', 'Salary Range From'].mean()

94981.0

In [9]:
data.loc[data['Level'] == '0', 'Salary Range From'].mean()

41428.58140084033

In [7]:
float((data['Level'] == 'M6').sum()) / data.shape[0]

0.0026021337496747333

In [11]:
float((data['Level'] == '0').sum()) / data.shape[0]

0.37158469945355194

In [21]:
ages1 = data.loc[data['Salary Range From'] > 60000, '# Of Positions']
ages2 = data.loc[data['Salary Range From'] <= 60000, '# Of Positions']
print("{0}, {1} ".format(
    round(ages1.sum()),
    round(ages2.sum()),
))

2578, 7037

In [27]:
data.loc[data['Salary Range To'] >= 100000, 'Level'].unique()

array(['M3', '0', '4', 'M1', '3', 'M7', 'M2', '2', 'M4', 'M5', '4B', 'M9',
       '4A', '1', 'M6', 'M8'], dtype=object)

In [35]:
data.loc[data['Salary Range To'] >= 180000, 'Level'].unique()

array(['M7', '0', 'M4', 'M5', 'M9', 'M3', 'M6', 'M8'], dtype=object)

In [31]:
data.loc[data['Salary Range To'] >= 220000, 'Level'].unique()

array(['M7', 'M9', 'M6', 'M8'], dtype=object)

In [52]:
for level in data.groupby(['Level'])['# Of Positions'].sum():
    print("level: {0}".format(level))

level: 5786
level: 1676
level: 8
level: 4
level: 937
level: 554
level: 4
level: 77
level: 8
level: 11
level: 191
level: 146
level: 100
level: 50
level: 37
level: 10
level: 12
level: 2
level: 2

In [57]:
for (level, agency), sub_df in data.groupby(['Level', 'Agency']):
    print("Level: {0}, agency: {1}".format(level, agency))
    print(sub_df['Job Category'].describe())

Level: 0, agency: ADMIN FOR CHILDREN'S SVCS
count                  44
unique                  8
top       Social Services
freq                   15
Name: Job Category, dtype: object
Level: 0, agency: ADMIN TRIALS AND HEARINGS
count                                   18
unique                                   2
top       Administration & Human Resources
freq                                    10
Name: Job Category, dtype: object
Level: 0, agency: BOARD OF CORRECTION
count                                                     2
unique                                                    1
top       Constituent Services & Community Programs Poli...
freq                                                      2
Name: Job Category, dtype: object
Level: 0, agency: BOROUGH PRESIDENT-QUEENS
count                                         2
unique                                        1
top       Engineering, Architecture, & Planning
freq                                          2
Name: Job Category, dtype: object
Level: 0, agency: BUSINESS INTEGRITY COMMISSION
count                                                     4
unique                                                    2
top       Policy, Research & Analysis Public Safety, Ins...
freq                                                      2
Name: Job Category, dtype: object
Level: 0, agency: CIVILIAN COMPLAINT REVIEW BD
count                                                     6
unique                                                    3
top       Communications & Intergovernmental Affairs Leg...
freq                                                      2
Name: Job Category, dtype: object
Level: 0, agency: CONSUMER AFFAIRS
count                                                    10
unique                                                    5
top       Constituent Services & Community Programs Lega...
freq                                                      2
Name: Job Category, dtype: object
Level: 0, agency: DEPARTMENT FOR THE AGING
count                                      4
unique                                     1
top       Finance, Accounting, & Procurement
freq                                       4
Name: Job Category, dtype: object
Level: 0, agency: DEPARTMENT OF BUILDINGS
count                                            18
unique                                            5
top       Public Safety, Inspections, & Enforcement
freq                                             10
Name: Job Category, dtype: object
Level: 0, agency: DEPARTMENT OF BUSINESS SERV.
count                                            30
unique                                            4
top       Constituent Services & Community Programs
freq                                             22
Name: Job Category, dtype: object
Level: 0, agency: DEPARTMENT OF CITY PLANNING
count                                        16
unique                                        4
top       Engineering, Architecture, & Planning
freq                                          6
Name: Job Category, dtype: object
Level: 0, agency: DEPARTMENT OF CORRECTION
count                                   15
unique                                   5
top       Administration & Human Resources
freq                                     7
Name: Job Category, dtype: object
Level: 0, agency: DEPARTMENT OF FINANCE
count                              56
unique                              8
top       Policy, Research & Analysis
freq                               18
Name: Job Category, dtype: object
Level: 0, agency: DEPARTMENT OF INVESTIGATION
count                                                     2
unique                                                    1
top       Legal Affairs Public Safety, Inspections, & En...
freq                                                      2
Name: Job Category, dtype: object
Level: 0, agency: DEPARTMENT OF PROBATION
count                                              4
unique                                             2
top       Communications & Intergovernmental Affairs
freq                                               2
Name: Job Category, dtype: object
Level: 0, agency: DEPARTMENT OF SANITATION
count                                    20
unique                                    3
top       Building Operations & Maintenance
freq                                     16
Name: Job Category, dtype: object
Level: 0, agency: DEPARTMENT OF TRANSPORTATION
count                                        84
unique                                       19
top       Engineering, Architecture, & Planning
freq                                         18
Name: Job Category, dtype: object
Level: 0, agency: DEPT OF CITYWIDE ADMIN SVCS
count                                    4
unique                                   1
top       Administration & Human Resources
freq                                     4
Name: Job Category, dtype: object
Level: 0, agency: DEPT OF DESIGN & CONSTRUCTION
count                                        98
unique                                       13
top       Engineering, Architecture, & Planning
freq                                         61
Name: Job Category, dtype: object
Level: 0, agency: DEPT OF ENVIRONMENT PROTECTION
count                                       426
unique                                       33
top       Engineering, Architecture, & Planning
freq                                        149
Name: Job Category, dtype: object
Level: 0, agency: DEPT OF HEALTH/MENTAL HYGIENE
count        169
unique        17
top       Health
freq         109
Name: Job Category, dtype: object
Level: 0, agency: DEPT OF INFO TECH & TELECOMM
count                                53
unique                                9
top       Technology, Data & Innovation
freq                                 41
Name: Job Category, dtype: object
Level: 0, agency: DEPT OF PARKS & RECREATION
count                                    40
unique                                    5
top       Building Operations & Maintenance
freq                                     21
Name: Job Category, dtype: object
Level: 0, agency: DEPT OF YOUTH & COMM DEV SRVS
count                                             5
unique                                            3
top       Constituent Services & Community Programs
freq                                              3
Name: Job Category, dtype: object
Level: 0, agency: DISTRICT ATTORNEY KINGS COUNTY
count                                             8
unique                                            3
top       Legal Affairs Policy, Research & Analysis
freq                                              4
Name: Job Category, dtype: object
Level: 0, agency: DISTRICT ATTORNEY RICHMOND COU
count                                             2
unique                                            1
top       Legal Affairs Policy, Research & Analysis
freq                                              2
Name: Job Category, dtype: object
Level: 0, agency: FINANCIAL INFO SVCS AGENCY
count                                29
unique                                2
top       Technology, Data & Innovation
freq                                 28
Name: Job Category, dtype: object
Level: 0, agency: FIRE DEPARTMENT
count                                 4
unique                                1
top       Technology, Data & Innovation
freq                                  4
Name: Job Category, dtype: object
Level: 0, agency: HOUSING PRESERVATION & DVLPMNT
count                                   49
unique                                   6
top       Administration & Human Resources
freq                                    17
Name: Job Category, dtype: object
Level: 0, agency: HRA/DEPT OF SOCIAL SERVICES
count                  13
unique                  3
top       Social Services
freq                    7
Name: Job Category, dtype: object
Level: 0, agency: HUMAN RIGHTS COMMISSION
count                                                     8
unique                                                    4
top       Constituent Services & Community Programs Comm...
freq                                                      2
Name: Job Category, dtype: object
Level: 0, agency: LAW DEPARTMENT
count                54
unique               11
top       Legal Affairs
freq                 37
Name: Job Category, dtype: object
Level: 0, agency: MANHATTAN COMMUNITY BOARD #10
count                                             2
unique                                            1
top       Constituent Services & Community Programs
freq                                              2
Name: Job Category, dtype: object
Level: 0, agency: MANHATTAN COMMUNITY BOARD #8
count                                             2
unique                                            1
top       Constituent Services & Community Programs
freq                                              2
Name: Job Category, dtype: object
Level: 0, agency: MAYORS OFFICE OF CONTRACT SVCS
count                                 8
unique                                3
top       Technology, Data & Innovation
freq                                  4
Name: Job Category, dtype: object
Level: 0, agency: NYC EMPLOYEES RETIREMENT SYS
count                                    6
unique                                   1
top       Administration & Human Resources
freq                                     6
Name: Job Category, dtype: object
Level: 0, agency: NYC HOUSING AUTHORITY
count                                            60
unique                                           13
top       Constituent Services & Community Programs
freq                                             10
Name: Job Category, dtype: object
Level: 0, agency: NYC POLICE PENSION FUND
count                                    2
unique                                   1
top       Administration & Human Resources
freq                                     2
Name: Job Category, dtype: object
Level: 0, agency: OFF OF PAYROLL ADMINISTRATION
count                                                     1
unique                                                    1
top       Finance, Accounting, & Procurement Policy, Res...
freq                                                      1
Name: Job Category, dtype: object
Level: 0, agency: OFFICE OF THE COMPTROLLER
count                                      4
unique                                     2
top       Finance, Accounting, & Procurement
freq                                       2
Name: Job Category, dtype: object
Level: 0, agency: POLICE DEPARTMENT
count                                   12
unique                                   5
top       Administration & Human Resources
freq                                     8
Name: Job Category, dtype: object
Level: 0, agency: TAXI & LIMOUSINE COMMISSION
count                              34
unique                              5
top       Policy, Research & Analysis
freq                               22
Name: Job Category, dtype: object
Level: 1, agency: ADMIN FOR CHILDREN'S SVCS
count                                              15
unique                                              4
top       Information Technology & Telecommunications
freq                                                6
Name: Job Category, dtype: object
Level: 1, agency: ADMIN TRIALS AND HEARINGS
count                                    2
unique                                   1
top       Administration & Human Resources
freq                                     2
Name: Job Category, dtype: object
Level: 1, agency: BOROUGH PRESIDENT-QUEENS
count                                         4
unique                                        1
top       Engineering, Architecture, & Planning
freq                                          4
Name: Job Category, dtype: object
Level: 1, agency: CIVILIAN COMPLAINT REVIEW BD
count                                                     4
unique                                                    3
top       Constituent Services & Community Programs Lega...
freq                                                      2
Name: Job Category, dtype: object
Level: 1, agency: CONSUMER AFFAIRS
count                                                     2
unique                                                    1
top       Legal Affairs Policy, Research & Analysis Publ...
freq                                                      2
Name: Job Category, dtype: object
Level: 1, agency: DEPARTMENT OF BUILDINGS
count                                                  7
unique                                                 4
top       Administration & Human Resources Legal Affairs
freq                                                   2
Name: Job Category, dtype: object
Level: 1, agency: DEPARTMENT OF BUSINESS SERV.
count                                            30
unique                                            3
top       Constituent Services & Community Programs
freq                                             26
Name: Job Category, dtype: object
Level: 1, agency: DEPARTMENT OF CITY PLANNING
count                                                     2
unique                                                    1
top       Engineering, Architecture, & Planning Technolo...
freq                                                      2
Name: Job Category, dtype: object
Level: 1, agency: DEPARTMENT OF FINANCE
count                                      1
unique                                     1
top       Finance, Accounting, & Procurement
freq                                       1
Name: Job Category, dtype: object
Level: 1, agency: DEPARTMENT OF INVESTIGATION
count                                            28
unique                                            3
top       Public Safety, Inspections, & Enforcement
freq                                             24
Name: Job Category, dtype: object
Level: 1, agency: DEPARTMENT OF PROBATION
count                                      4
unique                                     2
top       Finance, Accounting, & Procurement
freq                                       2
Name: Job Category, dtype: object
Level: 1, agency: DEPARTMENT OF SANITATION
count                                         6
unique                                        2
top       Engineering, Architecture, & Planning
freq                                          4
Name: Job Category, dtype: object
Level: 1, agency: DEPARTMENT OF TRANSPORTATION
count                                                    39
unique                                                   11
top       Engineering, Architecture, & Planning Policy, ...
freq                                                      8
Name: Job Category, dtype: object
Level: 1, agency: DEPT OF CITYWIDE ADMIN SVCS
count                                         8
unique                                        2
top       Engineering, Architecture, & Planning
freq                                          4
Name: Job Category, dtype: object
Level: 1, agency: DEPT OF DESIGN & CONSTRUCTION
count                                        38
unique                                        6
top       Engineering, Architecture, & Planning
freq                                         10
Name: Job Category, dtype: object
Level: 1, agency: DEPT OF ENVIRONMENT PROTECTION
count                                       122
unique                                       19
top       Engineering, Architecture, & Planning
freq                                         32
Name: Job Category, dtype: object
Level: 1, agency: DEPT OF HEALTH/MENTAL HYGIENE
count        293
unique        17
top       Health
freq         157
Name: Job Category, dtype: object
Level: 1, agency: DEPT OF INFO TECH & TELECOMM
count                                23
unique                                5
top       Technology, Data & Innovation
freq                                 18
Name: Job Category, dtype: object
Level: 1, agency: DEPT OF PARKS & RECREATION
count                                         8
unique                                        2
top       Engineering, Architecture, & Planning
freq                                          5
Name: Job Category, dtype: object
Level: 1, agency: DEPT OF YOUTH & COMM DEV SRVS
count                                 2
unique                                1
top       Technology, Data & Innovation
freq                                  2
Name: Job Category, dtype: object
Level: 1, agency: DISTRICT ATTORNEY KINGS COUNTY
count                                 2
unique                                1
top       Technology, Data & Innovation
freq                                  2
Name: Job Category, dtype: object
Level: 1, agency: DISTRICT ATTORNEY RICHMOND COU
count                                 2
unique                                1
top       Technology, Data & Innovation
freq                                  2
Name: Job Category, dtype: object
Level: 1, agency: FINANCIAL INFO SVCS AGENCY
count                                 2
unique                                1
top       Technology, Data & Innovation
freq                                  2
Name: Job Category, dtype: object
Level: 1, agency: FIRE DEPARTMENT
count                                             2
unique                                            1
top       Public Safety, Inspections, & Enforcement
freq                                              2
Name: Job Category, dtype: object
Level: 1, agency: HOUSING PRESERVATION & DVLPMNT
count                                        24
unique                                        5
top       Engineering, Architecture, & Planning
freq                                          6
Name: Job Category, dtype: object
Level: 1, agency: HRA/DEPT OF SOCIAL SERVICES
count                                                    3
unique                                                   1
top       Administration & Human Resources Social Services
freq                                                     3
Name: Job Category, dtype: object
Level: 1, agency: HUMAN RIGHTS COMMISSION
count                 4
unique                1
top       Legal Affairs
freq                  4
Name: Job Category, dtype: object
Level: 1, agency: LANDMARKS PRESERVATION COMM
count                                         2
unique                                        1
top       Engineering, Architecture, & Planning
freq                                          2
Name: Job Category, dtype: object
Level: 1, agency: LAW DEPARTMENT
count                                             11
unique                                             6
top       Communications & Intergovernmental Affairs
freq                                               2
Name: Job Category, dtype: object
Level: 1, agency: MUNICIPAL WATER FIN AUTHORITY
count                                                     2
unique                                                    1
top       Finance, Accounting, & Procurement Policy, Res...
freq                                                      2
Name: Job Category, dtype: object
Level: 1, agency: NYC EMPLOYEES RETIREMENT SYS
count                                10
unique                                3
top       Technology, Data & Innovation
freq                                  6
Name: Job Category, dtype: object
Level: 1, agency: NYC HOUSING AUTHORITY
count                                         4
unique                                        1
top       Engineering, Architecture, & Planning
freq                                          4
Name: Job Category, dtype: object
Level: 1, agency: OFF OF PAYROLL ADMINISTRATION
count                                                     1
unique                                                    1
top       Technology, Data & Innovation Policy, Research...
freq                                                      1
Name: Job Category, dtype: object

Level: 1, agency: OFFICE OF EMERGENCY MANAGEMENT
count                                     14
unique                                     5
top       Finance, Accounting, & Procurement
freq                                       4
Name: Job Category, dtype: object
Level: 1, agency: OFFICE OF MANAGEMENT & BUDGET
count                                                    38
unique                                                    6
top       Finance, Accounting, & Procurement Policy, Res...
freq                                                     24
Name: Job Category, dtype: object
Level: 1, agency: OFFICE OF THE COMPTROLLER
count                                      8
unique                                     2
top       Finance, Accounting, & Procurement
freq                                       4
Name: Job Category, dtype: object
Level: 1, agency: POLICE DEPARTMENT
count                                    8
unique                                   3
top       Administration & Human Resources
freq                                     4
Name: Job Category, dtype: object
Level: 1, agency: PUBLIC ADMINISTRATOR-NEW YORK
count                                      1
unique                                     1
top       Finance, Accounting, & Procurement
freq                                       1
Name: Job Category, dtype: object
Level: 1, agency: TAXI & LIMOUSINE COMMISSION
count                22
unique                5
top       Legal Affairs
freq                  8
Name: Job Category, dtype: object
Level: 1A, agency: FIRE DEPARTMENT
count          2
unique         1
top       Health
freq           2
Name: Job Category, dtype: object
Level: 1B, agency: DEPT OF DESIGN & CONSTRUCTION
count                                         4
unique                                        2
top       Engineering, Architecture, & Planning
freq                                          2
Name: Job Category, dtype: object
Level: 2, agency: ADMIN FOR CHILDREN'S SVCS
count                                                    10
unique                                                    5
top       Public Safety, Inspections, & Enforcement Soci...
freq                                                      4
Name: Job Category, dtype: object
Level: 2, agency: ADMIN TRIALS AND HEARINGS
count                                                     1
unique                                                    1
top       Administration & Human Resources Constituent S...
freq                                                      1
Name: Job Category, dtype: object
Level: 2, agency: BOARD OF CORRECTION
count                                                     8
unique                                                    4
top       Administration & Human Resources Policy, Resea...
freq                                                      2
Name: Job Category, dtype: object
Level: 2, agency: DEPARTMENT OF BUILDINGS
count                                                     1
unique                                                    1
top       Administration & Human Resources Constituent S...
freq                                                      1
Name: Job Category, dtype: object
Level: 2, agency: DEPARTMENT OF BUSINESS SERV.
count                                             2
unique                                            1
top       Constituent Services & Community Programs
freq                                              2
Name: Job Category, dtype: object
Level: 2, agency: DEPARTMENT OF CITY PLANNING
count                                                     8
unique                                                    5
top       Engineering, Architecture, & Planning Policy, ...
freq                                                      2
Name: Job Category, dtype: object
Level: 2, agency: DEPARTMENT OF CORRECTION
count                10
unique                4
top       Legal Affairs
freq                  4
Name: Job Category, dtype: object
Level: 2, agency: DEPARTMENT OF INVESTIGATION
count                                            20
unique                                            5
top       Public Safety, Inspections, & Enforcement
freq                                             11
Name: Job Category, dtype: object
Level: 2, agency: DEPARTMENT OF PROBATION
count                 2
unique                1
top       Legal Affairs
freq                  2
Name: Job Category, dtype: object
Level: 2, agency: DEPARTMENT OF SANITATION
count                                    4
unique                                   2
top       Administration & Human Resources
freq                                     2
Name: Job Category, dtype: object
Level: 2, agency: DEPARTMENT OF TRANSPORTATION
count                                        36
unique                                        9
top       Engineering, Architecture, & Planning
freq                                         11
Name: Job Category, dtype: object
Level: 2, agency: DEPT OF CITYWIDE ADMIN SVCS
count                                         8
unique                                        2
top       Engineering, Architecture, & Planning
freq                                          4
Name: Job Category, dtype: object
Level: 2, agency: DEPT OF DESIGN & CONSTRUCTION
count                                        34
unique                                        6
top       Engineering, Architecture, & Planning
freq                                         22
Name: Job Category, dtype: object
Level: 2, agency: DEPT OF ENVIRONMENT PROTECTION
count                                       127
unique                                       21
top       Engineering, Architecture, & Planning
freq                                         47
Name: Job Category, dtype: object
Level: 2, agency: DEPT OF HEALTH/MENTAL HYGIENE
count        185
unique        14
top       Health
freq          94
Name: Job Category, dtype: object
Level: 2, agency: DEPT OF INFO TECH & TELECOMM
count                                19
unique                                3
top       Technology, Data & Innovation
freq                                 17
Name: Job Category, dtype: object
Level: 2, agency: DEPT OF PARKS & RECREATION
count                                         9
unique                                        2
top       Engineering, Architecture, & Planning
freq                                          6
Name: Job Category, dtype: object
Level: 2, agency: DEPT OF YOUTH & COMM DEV SRVS
count                                      4
unique                                     2
top       Finance, Accounting, & Procurement
freq                                       2
Name: Job Category, dtype: object
Level: 2, agency: DEPT. OF HOMELESS SERVICES
count                                                     1
unique                                                    1
top       Constituent Services & Community Programs Comm...
freq                                                      1
Name: Job Category, dtype: object
Level: 2, agency: FINANCIAL INFO SVCS AGENCY
count                                 3
unique                                2
top       Technology, Data & Innovation
freq                                  2
Name: Job Category, dtype: object
Level: 2, agency: FIRE DEPARTMENT
count          4
unique         2
top       Health
freq           2
Name: Job Category, dtype: object
Level: 2, agency: HOUSING PRESERVATION & DVLPMNT
count                                        29
unique                                        6
top       Engineering, Architecture, & Planning
freq                                          8
Name: Job Category, dtype: object
Level: 2, agency: HRA/DEPT OF SOCIAL SERVICES
count                  10
unique                  7
top       Social Services
freq                    3
Name: Job Category, dtype: object
Level: 2, agency: HUMAN RIGHTS COMMISSION
count                 6
unique                1
top       Legal Affairs
freq                  6
Name: Job Category, dtype: object
Level: 2, agency: LAW DEPARTMENT
count                24
unique                7
top       Legal Affairs
freq                 11
Name: Job Category, dtype: object
Level: 2, agency: NYC EMPLOYEES RETIREMENT SYS
count                                16
unique                                1
top       Technology, Data & Innovation
freq                                 16
Name: Job Category, dtype: object
Level: 2, agency: NYC HOUSING AUTHORITY
count                                        18
unique                                        3
top       Engineering, Architecture, & Planning
freq                                         12
Name: Job Category, dtype: object
Level: 2, agency: OFF OF PAYROLL ADMINISTRATION
count                                    5
unique                                   3
top       Administration & Human Resources
freq                                     2
Name: Job Category, dtype: object
Level: 2, agency: OFFICE OF MANAGEMENT & BUDGET
count                                                     4
unique                                                    2
top       Technology, Data & Innovation Policy, Research...
freq                                                      2
Name: Job Category, dtype: object
Level: 2, agency: OFFICE OF THE COMPTROLLER
count                                      6
unique                                     3
top       Finance, Accounting, & Procurement
freq                                       2
Name: Job Category, dtype: object
Level: 2, agency: POLICE DEPARTMENT
count                                                     2
unique                                                    2
top       Administration & Human Resources Finance, Acco...
freq                                                      1
Name: Job Category, dtype: object
Level: 2, agency: TAXI & LIMOUSINE COMMISSION
count                                14
unique                                2
top       Technology, Data & Innovation
freq                                  8
Name: Job Category, dtype: object
Level: 2, agency: TEACHERS RETIREMENT SYSTEM
count                                      2
unique                                     1
top       Finance, Accounting, & Procurement
freq                                       2
Name: Job Category, dtype: object
Level: 3, agency: ADMIN FOR CHILDREN'S SVCS
count                   6
unique                  1
top       Social Services
freq                    6
Name: Job Category, dtype: object
Level: 3, agency: BOARD OF CORRECTION
count                                                     2
unique                                                    1
top       Technology, Data & Innovation Policy, Research...
freq                                                      2
Name: Job Category, dtype: object
Level: 3, agency: CONSUMER AFFAIRS
count                                                     2
unique                                                    1
top       Legal Affairs Policy, Research & Analysis Soci...
freq                                                      2
Name: Job Category, dtype: object
Level: 3, agency: DEPARTMENT OF BUILDINGS
count                                                     2
unique                                                    2
top       Administration & Human Resources Constituent S...
freq                                                      1
Name: Job Category, dtype: object
Level: 3, agency: DEPARTMENT OF BUSINESS SERV.
count                                 4
unique                                2
top       Technology, Data & Innovation
freq                                  2
Name: Job Category, dtype: object
Level: 3, agency: DEPARTMENT OF CITY PLANNING
count                                                     7
unique                                                    3
top       Technology, Data & Innovation Policy, Research...
freq                                                      4
Name: Job Category, dtype: object
Level: 3, agency: DEPARTMENT OF CORRECTION
count                 3
unique                2
top       Legal Affairs
freq                  2
Name: Job Category, dtype: object
Level: 3, agency: DEPARTMENT OF INVESTIGATION
count                                             7
unique                                            3
top       Public Safety, Inspections, & Enforcement
freq                                              4
Name: Job Category, dtype: object
Level: 3, agency: DEPARTMENT OF SANITATION
count                                         4
unique                                        2
top       Engineering, Architecture, & Planning
freq                                          2
Name: Job Category, dtype: object
Level: 3, agency: DEPARTMENT OF TRANSPORTATION
count                                        31
unique                                       11
top       Engineering, Architecture, & Planning
freq                                         15
Name: Job Category, dtype: object
Level: 3, agency: DEPT OF DESIGN & CONSTRUCTION
count                                        10
unique                                        2
top       Engineering, Architecture, & Planning
freq                                          8
Name: Job Category, dtype: object
Level: 3, agency: DEPT OF ENVIRONMENT PROTECTION
count                                        69
unique                                       14
top       Engineering, Architecture, & Planning
freq                                         19
Name: Job Category, dtype: object
Level: 3, agency: DEPT OF HEALTH/MENTAL HYGIENE
count        111
unique         9
top       Health
freq          65
Name: Job Category, dtype: object
Level: 3, agency: DEPT OF INFO TECH & TELECOMM
count                                18
unique                                3
top       Technology, Data & Innovation
freq                                 16
Name: Job Category, dtype: object
Level: 3, agency: DEPT OF PARKS & RECREATION
count                                         1
unique                                        1
top       Engineering, Architecture, & Planning
freq                                          1
Name: Job Category, dtype: object
Level: 3, agency: FINANCIAL INFO SVCS AGENCY
count                                    1
unique                                   1
top       Administration & Human Resources
freq                                     1
Name: Job Category, dtype: object
Level: 3, agency: FIRE DEPARTMENT
count                 5
unique                2
top       Legal Affairs
freq                  3
Name: Job Category, dtype: object
Level: 3, agency: HOUSING PRESERVATION & DVLPMNT
count                                11
unique                                4
top       Technology, Data & Innovation
freq                                  4
Name: Job Category, dtype: object
Level: 3, agency: HRA/DEPT OF SOCIAL SERVICES
count                  11
unique                  5
top       Social Services
freq                    6
Name: Job Category, dtype: object
Level: 3, agency: LAW DEPARTMENT
count                35
unique                7
top       Legal Affairs
freq                 21
Name: Job Category, dtype: object
Level: 3, agency: NYC EMPLOYEES RETIREMENT SYS
count                                 8
unique                                1
top       Technology, Data & Innovation
freq                                  8
Name: Job Category, dtype: object
Level: 3, agency: NYC HOUSING AUTHORITY
count                                        20
unique                                        5
top       Engineering, Architecture, & Planning
freq                                          8
Name: Job Category, dtype: object
Level: 3, agency: OFF OF PAYROLL ADMINISTRATION
count                                                     2
unique                                                    1
top       Administration & Human Resources Technology, D...
freq                                                      2
Name: Job Category, dtype: object
Level: 3, agency: OFFICE OF THE COMPTROLLER
count                                      4
unique                                     1
top       Finance, Accounting, & Procurement
freq                                       4
Name: Job Category, dtype: object
Level: 3, agency: POLICE DEPARTMENT
count                                                     2
unique                                                    2
top       Administration & Human Resources Finance, Acco...
freq                                                      1
Name: Job Category, dtype: object
Level: 3, agency: TAX COMMISSION
count                                 2
unique                                1
top       Technology, Data & Innovation
freq                                  2
Name: Job Category, dtype: object
Level: 3, agency: TAXI & LIMOUSINE COMMISSION
count                                10
unique                                3
top       Technology, Data & Innovation
freq                                  5
Name: Job Category, dtype: object
Level: 3A, agency: DEPT OF HEALTH/MENTAL HYGIENE
count                                    4
unique                                   2
top       Administration & Human Resources
freq                                     2
Name: Job Category, dtype: object
Level: 4, agency: DEPARTMENT OF BUILDINGS
count                                                     1
unique                                                    1
top       Administration & Human Resources Finance, Acco...
freq                                                      1
Name: Job Category, dtype: object
Level: 4, agency: DEPARTMENT OF CITY PLANNING
count                                                     1
unique                                                    1
top       Engineering, Architecture, & Planning Policy, ...
freq                                                      1
Name: Job Category, dtype: object
Level: 4, agency: DEPARTMENT OF CORRECTION
count                 1
unique                1
top       Legal Affairs
freq                  1
Name: Job Category, dtype: object
Level: 4, agency: DEPARTMENT OF FINANCE
count                                      1
unique                                     1
top       Finance, Accounting, & Procurement
freq                                       1
Name: Job Category, dtype: object
Level: 4, agency: DEPARTMENT OF SANITATION
count                                 2
unique                                1
top       Technology, Data & Innovation
freq                                  2
Name: Job Category, dtype: object
Level: 4, agency: DEPARTMENT OF TRANSPORTATION
count                                    1
unique                                   1
top       Administration & Human Resources
freq                                     1
Name: Job Category, dtype: object
Level: 4, agency: DEPT OF DESIGN & CONSTRUCTION
count                                         6
unique                                        3
top       Engineering, Architecture, & Planning
freq                                          2
Name: Job Category, dtype: object
Level: 4, agency: DEPT OF ENVIRONMENT PROTECTION
count                                        17
unique                                        9
top       Engineering, Architecture, & Planning
freq                                          4
Name: Job Category, dtype: object
Level: 4, agency: DEPT OF HEALTH/MENTAL HYGIENE
count          7
unique         2
top       Health
freq           5
Name: Job Category, dtype: object
Level: 4, agency: DEPT OF INFO TECH & TELECOMM

count                                              14
unique                                              2
top       Information Technology & Telecommunications
freq                                                7
Name: Job Category, dtype: object
Level: 4, agency: FIRE DEPARTMENT
count                                      1
unique                                     1
top       Finance, Accounting, & Procurement
freq                                       1
Name: Job Category, dtype: object
Level: 4, agency: HOUSING PRESERVATION & DVLPMNT
count                                 4
unique                                1
top       Technology, Data & Innovation
freq                                  4
Name: Job Category, dtype: object
Level: 4, agency: NYC EMPLOYEES RETIREMENT SYS
count                                               8
unique                                              2
top       Information Technology & Telecommunications
freq                                                6
Name: Job Category, dtype: object
Level: 4A, agency: DEPT OF HEALTH/MENTAL HYGIENE
count                                      6
unique                                     1
top       Health Policy, Research & Analysis
freq                                       6
Name: Job Category, dtype: object
Level: 4A, agency: EQUAL EMPLOY PRACTICES COMM
count                                              2
unique                                             1
top       Communications & Intergovernmental Affairs
freq                                               2
Name: Job Category, dtype: object
Level: 4B, agency: DEPT OF HEALTH/MENTAL HYGIENE
count                                     11
unique                                     4
top       Health Policy, Research & Analysis
freq                                       5
Name: Job Category, dtype: object
Level: M1, agency: ADMIN FOR CHILDREN'S SVCS
count                   6
unique                  1
top       Social Services
freq                    6
Name: Job Category, dtype: object
Level: M1, agency: BUSINESS INTEGRITY COMMISSION
count                                 3
unique                                1
top       Technology, Data & Innovation
freq                                  3
Name: Job Category, dtype: object
Level: M1, agency: DEPARTMENT OF BUILDINGS
count                                 2
unique                                1
top       Technology, Data & Innovation
freq                                  2
Name: Job Category, dtype: object
Level: M1, agency: DEPARTMENT OF BUSINESS SERV.
count                                             2
unique                                            1
top       Constituent Services & Community Programs
freq                                              2
Name: Job Category, dtype: object
Level: M1, agency: DEPARTMENT OF CITY PLANNING
count                                                     2
unique                                                    1
top       Technology, Data & Innovation Policy, Research...
freq                                                      2
Name: Job Category, dtype: object
Level: M1, agency: DEPARTMENT OF CORRECTION
count                                12
unique                                2
top       Technology, Data & Innovation
freq                                  8
Name: Job Category, dtype: object
Level: M1, agency: DEPARTMENT OF INVESTIGATION
count                                                     6
unique                                                    3
top       Communications & Intergovernmental Affairs Pub...
freq                                                      2
Name: Job Category, dtype: object
Level: M1, agency: DEPARTMENT OF SANITATION
count                                 2
unique                                1
top       Technology, Data & Innovation
freq                                  2
Name: Job Category, dtype: object
Level: M1, agency: DEPARTMENT OF TRANSPORTATION
count                                    2
unique                                   1
top       Administration & Human Resources
freq                                     2
Name: Job Category, dtype: object
Level: M1, agency: DEPT OF DESIGN & CONSTRUCTION
count                                 4
unique                                2
top       Technology, Data & Innovation
freq                                  2
Name: Job Category, dtype: object
Level: M1, agency: DEPT OF ENVIRONMENT PROTECTION
count                21
unique                7
top       Legal Affairs
freq                  7
Name: Job Category, dtype: object
Level: M1, agency: DEPT OF HEALTH/MENTAL HYGIENE
count         27
unique         8
top       Health
freq          11
Name: Job Category, dtype: object
Level: M1, agency: DEPT OF INFO TECH & TELECOMM
count                                 7
unique                                2
top       Technology, Data & Innovation
freq                                  6
Name: Job Category, dtype: object
Level: M1, agency: DEPT OF YOUTH & COMM DEV SRVS
count                                 2
unique                                1
top       Technology, Data & Innovation
freq                                  2
Name: Job Category, dtype: object
Level: M1, agency: FINANCIAL INFO SVCS AGENCY
count                                 2
unique                                1
top       Technology, Data & Innovation
freq                                  2
Name: Job Category, dtype: object
Level: M1, agency: HOUSING PRESERVATION & DVLPMNT
count                                14
unique                                3
top       Technology, Data & Innovation
freq                                  8
Name: Job Category, dtype: object
Level: M1, agency: HRA/DEPT OF SOCIAL SERVICES
count                                 3
unique                                2
top       Legal Affairs Social Services
freq                                  2
Name: Job Category, dtype: object
Level: M1, agency: HUMAN RIGHTS COMMISSION
count                 8
unique                2
top       Legal Affairs
freq                  6
Name: Job Category, dtype: object
Level: M1, agency: LANDMARKS PRESERVATION COMM
count                                         2
unique                                        1
top       Engineering, Architecture, & Planning
freq                                          2
Name: Job Category, dtype: object
Level: M1, agency: MAYORS OFFICE OF CONTRACT SVCS
count                                22
unique                                5
top       Technology, Data & Innovation
freq                                 14
Name: Job Category, dtype: object
Level: M1, agency: NYC EMPLOYEES RETIREMENT SYS
count                                 8
unique                                2
top       Technology, Data & Innovation
freq                                  6
Name: Job Category, dtype: object
Level: M1, agency: NYC HOUSING AUTHORITY
count                                 4
unique                                2
top       Technology, Data & Innovation
freq                                  2
Name: Job Category, dtype: object
Level: M1, agency: OFFICE OF THE COMPTROLLER
count                                 4
unique                                2
top       Technology, Data & Innovation
freq                                  2
Name: Job Category, dtype: object
Level: M1, agency: POLICE DEPARTMENT
count                                      2
unique                                     2
top       Finance, Accounting, & Procurement
freq                                       1
Name: Job Category, dtype: object
Level: M1, agency: PRESIDENT BOROUGH OF MANHATTAN
count                                              2
unique                                             1
top       Communications & Intergovernmental Affairs
freq                                               2
Name: Job Category, dtype: object
Level: M1, agency: TAXI & LIMOUSINE COMMISSION
count                                             2
unique                                            1
top       Public Safety, Inspections, & Enforcement
freq                                              2
Name: Job Category, dtype: object
Level: M2, agency: ADMIN FOR CHILDREN'S SVCS
count                   6
unique                  1
top       Social Services
freq                    6
Name: Job Category, dtype: object
Level: M2, agency: DEPARTMENT OF BUSINESS SERV.
count                                            18
unique                                            2
top       Constituent Services & Community Programs
freq                                             16
Name: Job Category, dtype: object
Level: M2, agency: DEPARTMENT OF FINANCE
count                                                     2
unique                                                    1
top       Communications & Intergovernmental Affairs Fin...
freq                                                      2
Name: Job Category, dtype: object
Level: M2, agency: DEPARTMENT OF TRANSPORTATION
count                                                     2
unique                                                    1
top       Engineering, Architecture, & Planning Building...
freq                                                      2
Name: Job Category, dtype: object
Level: M2, agency: DEPT OF DESIGN & CONSTRUCTION
count                                        19
unique                                        4
top       Engineering, Architecture, & Planning
freq                                         13
Name: Job Category, dtype: object
Level: M2, agency: DEPT OF ENVIRONMENT PROTECTION
count                                        20
unique                                        2
top       Engineering, Architecture, & Planning
freq                                         18
Name: Job Category, dtype: object
Level: M2, agency: DEPT OF HEALTH/MENTAL HYGIENE
count         11
unique         2
top       Health
freq           8
Name: Job Category, dtype: object
Level: M2, agency: DEPT OF INFO TECH & TELECOMM
count                                 7
unique                                2
top       Technology, Data & Innovation
freq                                  6
Name: Job Category, dtype: object
Level: M2, agency: HRA/DEPT OF SOCIAL SERVICES
count                                 3
unique                                2
top       Legal Affairs Social Services
freq                                  2
Name: Job Category, dtype: object
Level: M2, agency: HUMAN RIGHTS COMMISSION
count                                              2
unique                                             1
top       Communications & Intergovernmental Affairs
freq                                               2
Name: Job Category, dtype: object
Level: M2, agency: MAYORS OFFICE OF CONTRACT SVCS
count                                 4
unique                                1
top       Technology, Data & Innovation
freq                                  4
Name: Job Category, dtype: object
Level: M2, agency: NYC HOUSING AUTHORITY
count                                        10
unique                                        2
top       Engineering, Architecture, & Planning
freq                                          6
Name: Job Category, dtype: object
Level: M2, agency: OFFICE OF THE COMPTROLLER
count                18
unique                5
top       Legal Affairs
freq                  6
Name: Job Category, dtype: object
Level: M2, agency: POLICE DEPARTMENT
count                                             3
unique                                            2
top       Public Safety, Inspections, & Enforcement
freq                                              2
Name: Job Category, dtype: object
Level: M3, agency: ADMIN FOR CHILDREN'S SVCS
count                   1
unique                  1
top       Social Services
freq                    1
Name: Job Category, dtype: object
Level: M3, agency: DEPARTMENT OF BUSINESS SERV.
count                                             8
unique                                            2
top       Constituent Services & Community Programs
freq                                              6
Name: Job Category, dtype: object
Level: M3, agency: DEPT OF DESIGN & CONSTRUCTION
count                                         4
unique                                        1
top       Engineering, Architecture, & Planning
freq                                          4
Name: Job Category, dtype: object
Level: M3, agency: DEPT OF ENVIRONMENT PROTECTION
count                                        29
unique                                        5
top       Engineering, Architecture, & Planning
freq                                         11
Name: Job Category, dtype: object
Level: M3, agency: DEPT OF HEALTH/MENTAL HYGIENE
count          6
unique         3
top       Health
freq           2
Name: Job Category, dtype: object
Level: M3, agency: DEPT OF INFO TECH & TELECOMM
count                                11
unique                                1
top       Technology, Data & Innovation
freq                                 11
Name: Job Category, dtype: object
Level: M3, agency: DEPT OF YOUTH & COMM DEV SRVS
count                                             1
unique                                            1
top       Constituent Services & Community Programs
freq                                              1
Name: Job Category, dtype: object
Level: M3, agency: HRA/DEPT OF SOCIAL SERVICES
count                                                 4
unique                                                1
top       Technology, Data & Innovation Social Services
freq                                                  4
Name: Job Category, dtype: object
Level: M3, agency: LANDMARKS PRESERVATION COMM
count                                         2
unique                                        1
top       Engineering, Architecture, & Planning
freq                                          2
Name: Job Category, dtype: object
Level: M3, agency: MAYORS OFFICE OF CONTRACT SVCS
count                                                     6
unique                                                    3
top       Finance, Accounting, & Procurement Technology,...
freq                                                      2
Name: Job Category, dtype: object
Level: M3, agency: NYC EMPLOYEES RETIREMENT SYS
count                                 2
unique                                1
top       Technology, Data & Innovation
freq                                  2
Name: Job Category, dtype: object
Level: M3, agency: NYC HOUSING AUTHORITY
count                                        12
unique                                        3
top       Engineering, Architecture, & Planning
freq                                          8
Name: Job Category, dtype: object
Level: M3, agency: OFFICE OF MANAGEMENT & BUDGET
count                                                     2
unique                                                    1
top       Administration & Human Resources Policy, Resea...
freq                                                      2
Name: Job Category, dtype: object
Level: M3, agency: OFFICE OF THE ACTUARY
count                                                     2
unique                                                    1
top       Administration & Human Resources Communication...
freq                                                      2
Name: Job Category, dtype: object
Level: M3, agency: OFFICE OF THE COMPTROLLER
count                                 4
unique                                2
top       Technology, Data & Innovation
freq                                  2
Name: Job Category, dtype: object
Level: M3, agency: POLICE DEPARTMENT
count                                    1
unique                                   1
top       Administration & Human Resources
freq                                     1
Name: Job Category, dtype: object
Level: M4, agency: BUSINESS INTEGRITY COMMISSION
count                                             2
unique                                            1
top       Public Safety, Inspections, & Enforcement
freq                                              2
Name: Job Category, dtype: object
Level: M4, agency: CONSUMER AFFAIRS
count                                                     2
unique                                                    1
top       Constituent Services & Community Programs Lega...
freq                                                      2
Name: Job Category, dtype: object
Level: M4, agency: DEPARTMENT FOR THE AGING
count                                                     2
unique                                                    1
top       Constituent Services & Community Programs Comm...
freq                                                      2
Name: Job Category, dtype: object
Level: M4, agency: DEPARTMENT OF BUSINESS SERV.
count                                             4
unique                                            1
top       Constituent Services & Community Programs
freq                                              4
Name: Job Category, dtype: object
Level: M4, agency: DEPARTMENT OF INVESTIGATION
count                                             2
unique                                            1
top       Public Safety, Inspections, & Enforcement
freq                                              2
Name: Job Category, dtype: object
Level: M4, agency: DEPT OF ENVIRONMENT PROTECTION
count                                                     8
unique                                                    3
top       Engineering, Architecture, & Planning Policy, ...
freq                                                      4
Name: Job Category, dtype: object
Level: M4, agency: DEPT OF INFO TECH & TELECOMM
count                                 2
unique                                1
top       Technology, Data & Innovation
freq                                  2
Name: Job Category, dtype: object
Level: M4, agency: DEPT OF PARKS & RECREATION
count                                     4
unique                                    1
top       Building Operations & Maintenance
freq                                      4
Name: Job Category, dtype: object
Level: M4, agency: HOUSING PRESERVATION & DVLPMNT
count                                             2
unique                                            1
top       Constituent Services & Community Programs
freq                                              2
Name: Job Category, dtype: object
Level: M4, agency: NYC HOUSING AUTHORITY
count                                        10
unique                                        4
top       Engineering, Architecture, & Planning
freq                                          4
Name: Job Category, dtype: object
Level: M4, agency: OFFICE OF MANAGEMENT & BUDGET
count                                                     2
unique                                                    1
top       Engineering, Architecture, & Planning Technolo...
freq                                                      2
Name: Job Category, dtype: object
Level: M4, agency: OFFICE OF THE COMPTROLLER
count                                      8
unique                                     2
top       Finance, Accounting, & Procurement
freq                                       6
Name: Job Category, dtype: object
Level: M4, agency: TAXI & LIMOUSINE COMMISSION
count                                 2
unique                                1
top       Technology, Data & Innovation
freq                                  2
Name: Job Category, dtype: object
Level: M5, agency: DEPARTMENT OF INVESTIGATION
count                                             2
unique                                            1
top       Public Safety, Inspections, & Enforcement
freq                                              2
Name: Job Category, dtype: object

count                                   10
unique                                   4
top       Administration & Human Resources
freq                                     4
Name: Job Category, dtype: object
Level: M5, agency: NYC HOUSING AUTHORITY
count                               2
unique                              1
top       Policy, Research & Analysis
freq                                2
Name: Job Category, dtype: object
Level: M5, agency: OFFICE OF THE COMPTROLLER
count                                     10
unique                                     1
top       Finance, Accounting, & Procurement
freq                                      10
Name: Job Category, dtype: object
Level: M6, agency: DEPT OF HEALTH/MENTAL HYGIENE
count          6
unique         2
top       Health
freq           4
Name: Job Category, dtype: object
Level: M6, agency: POLICE DEPARTMENT
count                                                     4
unique                                                    2
top       Constituent Services & Community Programs Poli...
freq                                                      2
Name: Job Category, dtype: object
Level: M7, agency: DEPT OF ENVIRONMENT PROTECTION
count                                                     4
unique                                                    2
top       Engineering, Architecture, & Planning Maintena...
freq                                                      2
Name: Job Category, dtype: object
Level: M7, agency: NYC EMPLOYEES RETIREMENT SYS
count                                                     4
unique                                                    2
top       Administration & Human Resources Finance, Acco...
freq                                                      2
Name: Job Category, dtype: object
Level: M7, agency: NYC HOUSING AUTHORITY
count                 4
unique                2
top       Legal Affairs
freq                  2
Name: Job Category, dtype: object
Level: M8, agency: DEPT OF HEALTH/MENTAL HYGIENE
count          2
unique         1
top       Health
freq           2
Name: Job Category, dtype: object
Level: M9, agency: FINANCIAL INFO SVCS AGENCY
count                                                     2
unique                                                    1
top       Administration & Human Resources Finance, Acco...
freq                                                      2
Name: Job Category, dtype: object

In [58]:
data.loc[(data['Job Category'] == 'Social Services') &
     (data['Level'].isin(['M1', 'M2', 'M3', 'M4', 'M5', 'M6'])), 'Salary Range To'].value_counts()

97000.0     3
145991.0    2
110000.0    2
95000.0     2
94478.0     1
109100.0    1
150000.0    1
103044.0    1
Name: Salary Range To, dtype: int64

In [59]:
data.loc[(data['Job Category'] == 'Policy, Research & Analysis') &
     (data['Level'].isin(['M1', 'M2', 'M3', 'M4', 'M5', 'M6'])), 'Salary Range To'].value_counts()

208298.0    4
145000.0    2
105000.0    2
Name: Salary Range To, dtype: int64

In [60]:
data.loc[(data['Job Category'] == 'Social Services') &
     (data['Level'].str.startswith('M')), 'Salary Range To'].value_counts()

97000.0     3
145991.0    2
110000.0    2
95000.0     2
94478.0     1
109100.0    1
150000.0    1
103044.0    1
Name: Salary Range To, dtype: int64

In [47]:
data.groupby(['Level'])['# Of Positions'].sum()

Level
0     5786
1     1676
1A       8
1B       4
2      937
3      554
3A       4
4       77
4A       8
4B      11
M1     191
M2     146
M3     100
M4      50
M5      37
M6      10
M7      12
M8       2
M9       2
Name: # Of Positions, dtype: int64

In [61]:
data['Level'].value_counts()

0     1428
1      801
2      632
3      388
M1     171
M2     125
M3      96
4       64
M4      50
M5      33
M7      12
4B      11
M6      10
4A       8
3A       4
1B       4
M8       2
M9       2
1A       2
Name: Level, dtype: int64

In [84]:
mean_salary = data['Salary Range To'].mean()
print("Mean salary - {0}".format(max_salary))

top_vacansion_count = data[data['Salary Range To'] > mean_salary * 2].shape[0]
print("Count of 2x than mean vacansions - {0}".format(top_vacansion_count))

rich_share = float(data[(data['Salary Range To'] >= mean_salary * 2)
                 & (data['Level'].str.startswith('M'))].shape[0]) / top_vacansion_count
print("Percentage of rich managers {0}%".format(int(100 * rich_share)))

Mean salary - 75651.0
Count of 2x than mean vacansions - 197
Percentage of rich managers 92%

In [85]:
for (level), sub_df in data.groupby(['Level']):
    print(level, round(sub_df['Salary Range To'].mean(), 2))

0 63238.51
1 53902.45
1A 46211.0
1B 81526.0
2 79385.27
3 85230.22
3A 48939.5
4 94555.22
4A 112994.88
4B 100896.55
M1 114477.47
M2 125908.68
M3 153764.22
M4 153556.2
M5 169009.39
M6 225217.0
M7 217849.83
M8 230000.0
M9 226366.0

In [ ]:
pd.crosstab(data['native-country'], data['salary'], 
           values=data['hours-per-week'], aggfunc=np.mean).T

## Часть 2

In [11]:
from pandasql import sqldf
pysqldf = lambda q: sqldf(q, globals())

In [22]:
wind = (pd.read_csv('wind speed.csv', header=None,
                    names=["row", "UNIX", "date",
                           "time", "speed", "text"])
                    .drop("text", axis=1))
temp = (pd.read_csv('temperature.csv', header=None,
                    names=["row", "UNIX", "date",
                           "time", "temperature", "text"])
                    .drop("text", axis=1))

In [23]:
wind.head()

   row        UNIX        date      time  speed
0    1  1475315718  2016-09-30  23:55:18   7.87
1    2  1475315423  2016-09-30  23:50:23   7.87
2    3  1475315124  2016-09-30  23:45:24   9.00
3    4  1475314821  2016-09-30  23:40:21  13.50
4    5  1475314522  2016-09-30  23:35:22  15.75

In [24]:
wind.dtypes

row        int64
UNIX       int64
date      object
time      object
speed    float64
dtype: object

In [25]:
temp.head()

   row        UNIX        date      time  temperature
0    1  1475315718  2016-09-30  23:55:18           48
1    2  1475315423  2016-09-30  23:50:23           48
2    3  1475315124  2016-09-30  23:45:24           48
3    4  1475314821  2016-09-30  23:40:21           48
4    5  1475314522  2016-09-30  23:35:22           48

In [26]:
temp.dtypes

row             int64
UNIX            int64
date           object
time           object
temperature     int64
dtype: object

In [27]:
wind.merge(temp[["UNIX", "temperature"]], on="UNIX").head()

   row        UNIX        date      time  speed  temperature
0    1  1475315718  2016-09-30  23:55:18   7.87           48
1    2  1475315423  2016-09-30  23:50:23   7.87           48
2    3  1475315124  2016-09-30  23:45:24   9.00           48
3    4  1475314821  2016-09-30  23:40:21  13.50           48
4    5  1475314522  2016-09-30  23:35:22  15.75           48

In [28]:
%%timeit
wind.merge(temp[["UNIX", "temperature"]], on="UNIX")

13.2 ms ± 559 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [29]:
pysqldf("""SELECT w.row, w.UNIX, w.date, w.time,
                  w.speed, t.temperature
           FROM wind AS w JOIN temp AS t
           ON w.UNIX = t.UNIX
        """).head()

   row        UNIX        date      time  speed  temperature
0    1  1475315718  2016-09-30  23:55:18   7.87           48
1    2  1475315423  2016-09-30  23:50:23   7.87           48
2    3  1475315124  2016-09-30  23:45:24   9.00           48
3    4  1475314821  2016-09-30  23:40:21  13.50           48
4    5  1475314522  2016-09-30  23:35:22  15.75           48

In [30]:
%%timeit
pysqldf("""SELECT w.row, w.UNIX, w.date, w.time,
                  w.speed, t.temperature
           FROM wind AS w JOIN temp AS t
           ON w.UNIX = t.UNIX
        """)

672 ms ± 28.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [31]:
wind.groupby("date")["speed"].mean().head()

date
2016-09-01    6.396560
2016-09-02    5.804086
2016-09-03    4.960248
2016-09-04    5.184571
2016-09-05    5.830676
Name: speed, dtype: float64

In [32]:
%%timeit
wind.groupby("date")["speed"].mean()

2.36 ms ± 118 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [33]:
pysqldf("""SELECT date, AVG(speed)
           FROM wind
           GROUP BY date
        """).head()

         date  AVG(speed)
0  2016-09-01    6.396560
1  2016-09-02    5.804086
2  2016-09-03    4.960248
3  2016-09-04    5.184571
4  2016-09-05    5.830676

In [34]:
%%timeit
pysqldf("""SELECT date, AVG(speed)
           FROM wind
           GROUP BY date
        """)

253 ms ± 1.79 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)